name: Daily Github-Trending

on:
  # 手动触发
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Scraper
      run: |
        python main.py

    # Runs a set of commands using the runners shell
    - name: push to origin master
      run: |
        echo start push
        git config --global user.name "moko"
        git config --global user.email "no_moko@icloud.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
